2025-04-27 15:19:07 [31merror[39m: TypeError: connectToDb is not a function
    at Object.<anonymous> (C:\Users\Anjali\OneDrive\Documents\Food5\Food\food\backend\app.js:65:1)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (C:\Users\Anjali\OneDrive\Documents\Food5\Food\food\backend\server.js:24:13)
